"""
Embedded Cursor Canvas source for RSI-mean optimizer results.

Kept separate from optimize_rsi_mean.py so the TSX template (tooltips, charts)
stays readable and maintainable.
"""

from __future__ import annotations

from typing import Dict, Optional

from telegram_agent.rolling_window_metrics import rolling_metric_key_base


def build_rsi_mean_optimizer_canvas_tsx(
    s_meta: str,
    s_trials: str,
    *,
    metric_keys: Optional[Dict[str, str]] = None,
) -> str:
    mk = metric_keys or rolling_metric_key_base("1y")
    km = mk["median_return"]
    kf = mk["floor_return"]
    km_mean, km_min, km_max = f"{km}_mean", f"{km}_min", f"{km}_max"
    kf_mean, kf_min, kf_max = f"{kf}_mean", f"{kf}_min", f"{kf}_max"
    return (
        "import { useMemo, useState } from 'react';\n"
        "import { Card, CardBody, CardHeader, Divider, Grid, H1, H2, Row, Select, Stack, Stat, Table, Text, useCanvasState, useHostTheme } from 'cursor/canvas';\n"
        "\n"
        "type RowT = Record<string, any>;\n"
        f"const META = {s_meta} as any;\n"
        f"const ROWS: RowT[] = {s_trials} as any;\n"
        "\n"
        "function num(x: any): number | null {\n"
        "  const v = typeof x === 'number' ? x : (x === null || x === undefined ? NaN : Number(x));\n"
        "  return Number.isFinite(v) ? v : null;\n"
        "}\n"
        "\n"
        "function fmtVal(v: any): string {\n"
        "  if (v === null || v === undefined) return '';\n"
        "  if (typeof v === 'number') return String(Math.round(v * 1e9) / 1e9);\n"
        "  if (typeof v === 'boolean') return v ? 'true' : 'false';\n"
        "  if (typeof v === 'string') return v;\n"
        "  try {\n"
        "    return JSON.stringify(v);\n"
        "  } catch {\n"
        "    return String(v);\n"
        "  }\n"
        "}\n"
        "\n"
        "function rowTooltipText(row: RowT): string {\n"
        "  return Object.keys(row)\n"
        "    .sort((a, b) => a.localeCompare(b))\n"
        "    .map((k) => `${k}: ${fmtVal(row[k])}`)\n"
        "    .join('\\n');\n"
        "}\n"
        "\n"
        "type RRPoint = {\n"
        "  id: string;\n"
        "  x: number;\n"
        "  y: number;\n"
        "  xLo: number;\n"
        "  xHi: number;\n"
        "  yLo: number;\n"
        "  yHi: number;\n"
        "  ok: boolean;\n"
        "  row: RowT;\n"
        "};\n"
        "\n"
        "function buildRRPoints(\n"
        "  rows: RowT[],\n"
        "  xKey: string,\n"
        "  yKey: string,\n"
        "  xLoKey?: string,\n"
        "  xHiKey?: string,\n"
        "  yLoKey?: string,\n"
        "  yHiKey?: string,\n"
        "): RRPoint[] {\n"
        "  const out: RRPoint[] = [];\n"
        "  for (const r of rows) {\n"
        "    const xv = num(r[xKey]);\n"
        "    const yv = num(r[yKey]);\n"
        "    if (xv === null || yv === null) continue;\n"
        "    let xLo = xv;\n"
        "    let xHi = xv;\n"
        "    if (xLoKey && xHiKey) {\n"
        "      const a = num(r[xLoKey]);\n"
        "      const b = num(r[xHiKey]);\n"
        "      if (a !== null && b !== null) {\n"
        "        xLo = Math.min(a, b);\n"
        "        xHi = Math.max(a, b);\n"
        "      }\n"
        "    }\n"
        "    let yLo = yv;\n"
        "    let yHi = yv;\n"
        "    if (yLoKey && yHiKey) {\n"
        "      const a = num(r[yLoKey]);\n"
        "      const b = num(r[yHiKey]);\n"
        "      if (a !== null && b !== null) {\n"
        "        yLo = Math.min(a, b);\n"
        "        yHi = Math.max(a, b);\n"
        "      }\n"
        "    }\n"
        "    out.push({\n"
        "      id: String(r.param_set_index ?? ''),\n"
        "      x: xv,\n"
        "      y: yv,\n"
        "      xLo,\n"
        "      xHi,\n"
        "      yLo,\n"
        "      yHi,\n"
        "      ok: !!r.ok,\n"
        "      row: r,\n"
        "    });\n"
        "  }\n"
        "  return out;\n"
        "}\n"
        "\n"
        "type RiskScatterProps = {\n"
        "  rows: RowT[];\n"
        "  title: string;\n"
        "  subtitle?: string;\n"
        "  xKey: string;\n"
        "  yKey: string;\n"
        "  xLabel: string;\n"
        "  yLabel: string;\n"
        "  xLoKey?: string;\n"
        "  xHiKey?: string;\n"
        "  yLoKey?: string;\n"
        "  yHiKey?: string;\n"
        "};\n"
        "\n"
        "function RiskScatter(props: RiskScatterProps) {\n"
        "  const { tokens: t } = useHostTheme();\n"
        "  const { rows, title, subtitle, xKey, yKey, xLabel, yLabel, xLoKey, xHiKey, yLoKey, yHiKey } = props;\n"
        "  const pts = useMemo(\n"
        "    () => buildRRPoints(rows, xKey, yKey, xLoKey, xHiKey, yLoKey, yHiKey),\n"
        "    [rows, xKey, yKey, xLoKey, xHiKey, yLoKey, yHiKey],\n"
        "  );\n"
        "  const [hover, setHover] = useState<{ row: RowT; px: number; py: number } | null>(null);\n"
        "\n"
        "  const W = 980;\n"
        "  const H = 440;\n"
        "  const padL = 72;\n"
        "  const padR = 24;\n"
        "  const padT = 44;\n"
        "  const padB = 56;\n"
        "  const plotW = W - padL - padR;\n"
        "  const plotH = H - padT - padB;\n"
        "\n"
        "  if (!pts.length) {\n"
        "    return (\n"
        "      <Text tone=\"secondary\">\n"
        "        No points with valid {xLabel} and {yLabel}.\n"
        "      </Text>\n"
        "    );\n"
        "  }\n"
        "\n"
        "  const xs = pts.flatMap((p) => [p.x, p.xLo, p.xHi]);\n"
        "  const ys = pts.flatMap((p) => [p.y, p.yLo, p.yHi]);\n"
        "  let xMin = Math.min(...xs);\n"
        "  let xMax = Math.max(...xs);\n"
        "  let yMin = Math.min(...ys);\n"
        "  let yMax = Math.max(...ys);\n"
        "  const xPad = (xMax - xMin) * 0.06 + 1e-9;\n"
        "  const yPad = (yMax - yMin) * 0.1 + 1e-9;\n"
        "  xMin -= xPad;\n"
        "  xMax += xPad;\n"
        "  yMin -= yPad;\n"
        "  yMax += yPad;\n"
        "\n"
        "  const sx = (x: number) => padL + ((x - xMin) / (xMax - xMin)) * plotW;\n"
        "  const sy = (y: number) => padT + (1 - (y - yMin) / (yMax - yMin)) * plotH;\n"
        "\n"
        "  const xTicks = 5;\n"
        "  const yTicks = 5;\n"
        "  const xTickVals = Array.from({ length: xTicks + 1 }, (_, i) => xMin + (i * (xMax - xMin)) / xTicks);\n"
        "  const yTickVals = Array.from({ length: yTicks + 1 }, (_, i) => yMin + (i * (yMax - yMin)) / yTicks);\n"
        "\n"
        "  const vw = typeof window !== 'undefined' ? window.innerWidth : 1200;\n"
        "  const vh = typeof window !== 'undefined' ? window.innerHeight : 800;\n"
        "  const tw = 320;\n"
        "  const thMax = Math.min(420, vh * 0.72);\n"
        "  const tipLeft = hover ? Math.min(Math.max(8, hover.px + 14), vw - tw - 8) : 0;\n"
        "  const tipTop = hover ? Math.min(Math.max(8, hover.py + 14), vh - thMax - 8) : 0;\n"
        "  const tipText = hover ? rowTooltipText(hover.row) : '';\n"
        "\n"
        "  return (\n"
        "    <>\n"
        "      <svg width=\"100%\" viewBox={`0 0 ${W} ${H}`} style={{ border: `1px solid ${t.stroke.secondary}`, background: t.bg.editor }}>\n"
        "        <text x={padL} y={22} style={{ fill: t.text.primary, fontSize: 12, fontWeight: 600 }}>{title}</text>\n"
        "        {subtitle ? (\n"
        "          <text x={padL} y={40} style={{ fill: t.text.secondary, fontSize: 11 }}>{subtitle}</text>\n"
        "        ) : null}\n"
        "\n"
        "        <line x1={padL} y1={padT + plotH} x2={padL + plotW} y2={padT + plotH} stroke={t.stroke.secondary} />\n"
        "        <line x1={padL} y1={padT} x2={padL} y2={padT + plotH} stroke={t.stroke.secondary} />\n"
        "\n"
        "        {xTickVals.map((xv, i) => (\n"
        "          <g key={`xt-${i}`}>\n"
        "            <line x1={sx(xv)} y1={padT + plotH} x2={sx(xv)} y2={padT + plotH + 6} stroke={t.stroke.tertiary} />\n"
        "            <text x={sx(xv)} y={padT + plotH + 22} textAnchor=\"middle\" style={{ fill: t.text.secondary, fontSize: 10 }}>{xv.toFixed(3)}</text>\n"
        "          </g>\n"
        "        ))}\n"
        "\n"
        "        {yTickVals.map((yv, i) => (\n"
        "          <g key={`yt-${i}`}>\n"
        "            <line x1={padL - 6} y1={sy(yv)} x2={padL} y2={sy(yv)} stroke={t.stroke.tertiary} />\n"
        "            <text x={padL - 10} y={sy(yv) + 4} textAnchor=\"end\" style={{ fill: t.text.secondary, fontSize: 10 }}>{yv.toFixed(3)}</text>\n"
        "          </g>\n"
        "        ))}\n"
        "\n"
        "        <text x={padL + plotW / 2} y={H - 10} textAnchor=\"middle\" style={{ fill: t.text.secondary, fontSize: 11 }}>{xLabel}</text>\n"
        "        <text x={16} y={padT + plotH / 2} transform={`rotate(-90 16 ${padT + plotH / 2})`} textAnchor=\"middle\" style={{ fill: t.text.secondary, fontSize: 11 }}>{yLabel}</text>\n"
        "\n"
        "        {pts.map((p) => {\n"
        "          const cx = sx(p.x);\n"
        "          const cy = sy(p.y);\n"
        "          const yTop = sy(p.yHi);\n"
        "          const yBot = sy(p.yLo);\n"
        "          const xL = sx(p.xLo);\n"
        "          const xR = sx(p.xHi);\n"
        "          const fill = p.ok ? t.accent.primary : t.text.tertiary;\n"
        "          const hasYBand = Math.abs(p.yHi - p.yLo) > 1e-12;\n"
        "          const hasXBand = Math.abs(p.xHi - p.xLo) > 1e-12;\n"
        "          const onEnter = (e: any) => setHover({ row: p.row, px: e.clientX, py: e.clientY });\n"
        "          const onMove = (e: any) => setHover((h) => (h && h.row === p.row ? { row: p.row, px: e.clientX, py: e.clientY } : h));\n"
        "          const onLeave = () => setHover((h) => (h && h.row === p.row ? null : h));\n"
        "          return (\n"
        "            <g key={p.id}>\n"
        "              <title>{rowTooltipText(p.row)}</title>\n"
        "              {hasYBand ? (\n"
        "                <rect x={cx - 2.5} y={Math.min(yTop, yBot)} width={5} height={Math.abs(yBot - yTop)} fill={t.fill.quaternary} />\n"
        "              ) : null}\n"
        "              {hasXBand ? (\n"
        "                <rect x={Math.min(xL, xR)} y={cy - 2.5} width={Math.abs(xR - xL)} height={5} fill={t.fill.quaternary} />\n"
        "              ) : null}\n"
        "              {hasYBand ? (\n"
        "                <line x1={cx} y1={yTop} x2={cx} y2={yBot} stroke={t.stroke.secondary} strokeOpacity={0.55} strokeWidth={2} />\n"
        "              ) : null}\n"
        "              {hasXBand ? (\n"
        "                <line x1={xL} y1={cy} x2={xR} y2={cy} stroke={t.stroke.secondary} strokeOpacity={0.55} strokeWidth={2} />\n"
        "              ) : null}\n"
        "              <circle cx={cx} cy={cy} r={3.5} fill={fill} stroke={t.bg.editor} strokeWidth={1} />\n"
        "              <circle\n"
        "                cx={cx}\n"
        "                cy={cy}\n"
        "                r={16}\n"
        "                fill=\"transparent\"\n"
        "                style={{ cursor: 'pointer' }}\n"
        "                onMouseEnter={onEnter}\n"
        "                onMouseMove={onMove}\n"
        "                onMouseLeave={onLeave}\n"
        "              />\n"
        "            </g>\n"
        "          );\n"
        "        })}\n"
        "      </svg>\n"
        "      {hover ? (\n"
        "        <div\n"
        "          style={{\n"
        "            position: 'fixed',\n"
        "            left: tipLeft,\n"
        "            top: tipTop,\n"
        "            width: tw,\n"
        "            maxHeight: thMax,\n"
        "            overflow: 'auto',\n"
        "            zIndex: 1000,\n"
        "            pointerEvents: 'none',\n"
        "            padding: 10,\n"
        "            border: `1px solid ${t.stroke.secondary}`,\n"
        "            background: t.bg.elevated,\n"
        "            color: t.text.primary,\n"
        "            fontFamily: 'ui-monospace, Menlo, Monaco, Consolas, monospace',\n"
        "            fontSize: 10,\n"
        "            lineHeight: 1.35,\n"
        "            whiteSpace: 'pre-wrap',\n"
        "            wordBreak: 'break-word',\n"
        "          }}\n"
        "        >\n"
        "          {tipText}\n"
        "        </div>\n"
        "      ) : null}\n"
        "    </>\n"
        "  );\n"
        "}\n"
        "\n"
        "export default function RsiMeanOptimizerResults() {\n"
        "  const [limit, setLimit] = useCanvasState<string>('limit', '600');\n"
        "  const [sortKey, setSortKey] = useCanvasState<string>('sortKey', 'sharpe_mean');\n"
        "  const nLimit = Math.max(50, Math.min(5000, Number(limit) || 600));\n"
        "\n"
        "  const okCount = ROWS.filter((r) => !!r.ok).length;\n"
        "  const failCount = ROWS.length - okCount;\n"
        "\n"
        "  const sorted = [...ROWS]\n"
        "    .sort((a, b) => {\n"
        "      const va = num(a[sortKey]) ?? -1e18;\n"
        "      const vb = num(b[sortKey]) ?? -1e18;\n"
        "      return vb - va;\n"
        "    })\n"
        "    .slice(0, nLimit);\n"
        "\n"
        "  const tableCols = [\n"
        "    'param_set_index',\n"
        "    'attempts',\n"
        "    'ok',\n"
        "    'sharpe_mean',\n"
        f"    '{kf_mean}',\n"
        f"    '{kf_min}',\n"
        f"    '{kf_max}',\n"
        "    'objective_median',\n"
        "    'max_drawdown_max',\n"
        "  ];\n"
        "  const tableRows = sorted.map((r) =>\n"
        "    tableCols.map((c) => {\n"
        "      const v = r[c];\n"
        "      if (typeof v === 'number') return String(Math.round(v * 1e6) / 1e6);\n"
        "      return v === null || v === undefined ? '' : String(v);\n"
        "    }),\n"
        "  );\n"
        "\n"
        "  const sortOptions = [\n"
        "    { id: 'sharpe_mean', label: 'sharpe_mean' },\n"
        f"    {{ id: '{kf_mean}', label: '{kf_mean}' }},\n"
        f"    {{ id: '{km_mean}', label: '{km_mean}' }},\n"
        "    { id: 'max_drawdown_max', label: 'max_drawdown_max' },\n"
        "    { id: 'calmar_mean', label: 'calmar_mean' },\n"
        "    { id: 'objective_median', label: 'objective_median' },\n"
        "  ];\n"
        "\n"
        "  return (\n"
        "    <Stack gap={18}>\n"
        "      <H1>RSI-mean optimizer — risk vs reward</H1>\n"
        "      <Text tone=\"secondary\" size=\"small\">\n"
        "        Run: {String(META?.run_id || '')} • Window: {String(META?.window?.start || '')} → {String(META?.window?.end || '')}\n"
        "      </Text>\n"
        "\n"
        "      <Grid columns={4} gap={12}>\n"
        "        <Stat label=\"Param sets\" value={String(ROWS.length)} />\n"
        "        <Stat label=\"Feasible\" value={String(okCount)} tone={okCount > 0 ? 'success' : 'warning'} />\n"
        "        <Stat label=\"Infeasible\" value={String(failCount)} />\n"
        "        <Stat label=\"Rows (top N)\" value={String(sorted.length)} />\n"
        "      </Grid>\n"
        "\n"
        "      <H2>How to read risk vs reward</H2>\n"
        "      <Stack gap={6}>\n"
        "        <Text tone=\"secondary\" size=\"small\">\n"
        "          {`Median rolling return (${String(META?.rolling_metric_suffix || '1y')}) vs max drawdown is usually the most direct reward vs pain trade-off (higher and left is better).`}\n"
        "        </Text>\n"
        "        <Text tone=\"secondary\" size=\"small\">\n"
        "          Sharpe vs max drawdown mixes risk-adjusted quality with depth of loss; Calmar is similar when you trust the return denominator.\n"
        "        </Text>\n"
        "        <Text tone=\"secondary\" size=\"small\">\n"
        "          {`Rolling return floor (${String(META?.rolling_metric_suffix || '1y')}) vs Sharpe stresses left-tail outcomes vs volatility-adjusted mean; hit rate vs median return shows consistency vs central tendency.`}\n"
        "        </Text>\n"
        "        <Text tone=\"secondary\" size=\"small\">\n"
        "          Hover any point: tooltip lists every field on that param-set row (sorted keys). Native SVG title is also set for accessibility.\n"
        "        </Text>\n"
        "      </Stack>\n"
        "\n"
        "      <Row gap={12} align=\"center\">\n"
        "        <Select label=\"Sort table by\" value={sortKey} onChange={setSortKey} options={sortOptions} />\n"
        "        <Select\n"
        "          label=\"Show top N\"\n"
        "          value={String(limit)}\n"
        "          onChange={setLimit}\n"
        "          options={[100, 200, 400, 600, 1000, 2000, 5000].map((n) => ({ id: String(n), label: String(n) }))}\n"
        "        />\n"
        "      </Row>\n"
        "\n"
        "      <Card>\n"
        "        <CardHeader title={`Median rolling return (${String(META?.rolling_metric_suffix || '1y')}) vs max drawdown (mean)`} />\n"
        "        <CardBody>\n"
        "          <RiskScatter\n"
        "            rows={sorted}\n"
        "            title=\"Reward vs drawdown depth\"\n"
        "            subtitle={`Bands: min/max across attempts for drawdown (horizontal) and median rolling return (${String(META?.rolling_metric_suffix || '1y')}) (vertical).`}\n"
        "            xKey=\"max_drawdown_mean\"\n"
        f"            yKey=\"{km_mean}\"\n"
        "            xLoKey=\"max_drawdown_min\"\n"
        "            xHiKey=\"max_drawdown_max\"\n"
        f"            yLoKey=\"{km_min}\"\n"
        f"            yHiKey=\"{km_max}\"\n"
        "            xLabel=\"max_drawdown_mean (risk →)\"\n"
        f"            yLabel=\"{km_mean}\"\n"
        "          />\n"
        "        </CardBody>\n"
        "      </Card>\n"
        "\n"
        "      <Card>\n"
        "        <CardHeader title={`Sharpe (mean) vs rolling floor return (${String(META?.rolling_metric_suffix || '1y')}) (mean)`} />\n"
        "        <CardBody>\n"
        "          <RiskScatter\n"
        "            rows={sorted}\n"
        "            title=\"Risk-adjusted quality vs tail floor\"\n"
        "            subtitle={`Vertical band: min/max rolling floor return (${String(META?.rolling_metric_suffix || '1y')}) across attempts (no Sharpe min/max in aggregate rows).`}\n"
        "            xKey=\"sharpe_mean\"\n"
        f"            yKey=\"{kf_mean}\"\n"
        f"            yLoKey=\"{kf_min}\"\n"
        f"            yHiKey=\"{kf_max}\"\n"
        "            xLabel=\"sharpe_mean\"\n"
        f"            yLabel=\"{kf_mean}\"\n"
        "          />\n"
        "        </CardBody>\n"
        "      </Card>\n"
        "\n"
        "      <Divider />\n"
        "      <H2>Param-set table (top N)</H2>\n"
        "      <Table headers={tableCols} rows={tableRows} />\n"
        "    </Stack>\n"
        "  );\n"
        "}\n"
    )
